<?php
/**
 * YIARI Theme – ACF Field Groups
 * Semua field group didaftarkan via PHP agar portable (tidak bergantung JSON/DB).
 * Field group aktif berdasarkan Page Template yang dipilih.
 */

defined('ABSPATH') || exit;

add_action('acf/init', function () {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group([
        'key' => 'group_home',
        'title' => __('Home Page - Sections', 'yiari'),
        'location' => [[['param' => 'page_template', 'operator' => '==', 'value' => 'templates/home.php']]],
        'menu_order' => 10,
        'fields' => [
            ['key' => 'field_home_hero_tab', 'label' => __('Hero Section', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_home_hero_img', 'label' => __('Gambar Hero', 'yiari'), 'name' => 'hero_image', 'type' => 'image', 'return_format' => 'array', 'preview_size' => 'medium'],
            ['key' => 'field_home_hero_title', 'label' => __('Judul Hero', 'yiari'), 'name' => 'hero_title', 'type' => 'text', 'default_value' => __('Bersama Selamatkan Alam', 'yiari')],
            ['key' => 'field_home_hero_subtitle', 'label' => __('Subtitle Hero', 'yiari'), 'name' => 'hero_subtitle', 'type' => 'textarea', 'rows' => 2, 'default_value' => __('Bersama kita bisa menjaga satwa liar tetap hidup di alamnya', 'yiari')],
            ['key' => 'field_home_hero_cta_text', 'label' => __('Teks Tombol CTA', 'yiari'), 'name' => 'hero_cta_text', 'type' => 'text', 'default_value' => __('Donasi Sekarang', 'yiari')],
            ['key' => 'field_home_hero_cta_url', 'label' => __('URL Tombol CTA', 'yiari'), 'name' => 'hero_cta_url', 'type' => 'url'],

            ['key' => 'field_home_stats_tab', 'label' => __('Stats Section', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_home_stats_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'stats_label', 'type' => 'text', 'default_value' => __('DAMPAK TERUKUR', 'yiari')],
            ['key' => 'field_home_stats_title', 'label' => __('Judul', 'yiari'), 'name' => 'stats_title', 'type' => 'text', 'default_value' => __('Bukti Nyata Konservasi Kami', 'yiari')],
            ['key' => 'field_home_stats_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'stats_desc', 'type' => 'textarea', 'rows' => 3],
            [
                'key' => 'field_home_stats_items', 'label' => __('Item Statistik', 'yiari'), 'name' => 'stats_items',
                'type' => 'repeater', 'min' => 1, 'max' => 8, 'layout' => 'table',
                'button_label' => __('Tambah Statistik', 'yiari'),
                'sub_fields' => [
                    ['key' => 'field_stat_number', 'label' => __('Angka', 'yiari'), 'name' => 'number', 'type' => 'number', 'column_width' => '20'],
                    ['key' => 'field_stat_suffix', 'label' => __('Suffix', 'yiari'), 'name' => 'suffix', 'type' => 'text', 'column_width' => '10', 'placeholder' => '+'],
                    ['key' => 'field_stat_label', 'label' => __('Label', 'yiari'), 'name' => 'label', 'type' => 'text', 'column_width' => '70'],
                ],
            ],

            ['key' => 'field_home_crisis_tab', 'label' => __('Krisis Section', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_home_crisis_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'crisis_label', 'type' => 'text', 'default_value' => __('ANCAMAN MENDESAK', 'yiari')],
            ['key' => 'field_home_crisis_title', 'label' => __('Judul', 'yiari'), 'name' => 'crisis_title', 'type' => 'text', 'default_value' => __('3 Krisis yang Kita Hadapi Bersama', 'yiari')],
            ['key' => 'field_home_crisis_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'crisis_desc', 'type' => 'textarea', 'rows' => 3],
            [
                'key' => 'field_home_crisis_cards', 'label' => __('Kartu Krisis', 'yiari'), 'name' => 'crisis_cards',
                'type' => 'repeater', 'min' => 1, 'max' => 4, 'layout' => 'row',
                'button_label' => __('Tambah Kartu Krisis', 'yiari'),
                'sub_fields' => [
                    ['key' => 'field_crisis_img', 'label' => __('Gambar', 'yiari'), 'name' => 'image', 'type' => 'image', 'return_format' => 'array'],
                    ['key' => 'field_crisis_title', 'label' => __('Judul', 'yiari'), 'name' => 'title', 'type' => 'text'],
                    ['key' => 'field_crisis_text', 'label' => __('Deskripsi', 'yiari'), 'name' => 'text', 'type' => 'textarea', 'rows' => 3],
                ],
            ],

            ['key' => 'field_home_story_tab', 'label' => __('Story Section', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_home_story_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'story_label', 'type' => 'text', 'default_value' => __('DARI LAPANGAN', 'yiari')],
            ['key' => 'field_home_story_title', 'label' => __('Judul', 'yiari'), 'name' => 'story_title', 'type' => 'text'],
            ['key' => 'field_home_story_para1', 'label' => __('Paragraf 1', 'yiari'), 'name' => 'story_para1', 'type' => 'textarea', 'rows' => 4],
            ['key' => 'field_home_story_para2', 'label' => __('Paragraf 2', 'yiari'), 'name' => 'story_para2', 'type' => 'textarea', 'rows' => 4],
            ['key' => 'field_home_story_btn1_text', 'label' => __('Tombol 1 - Teks', 'yiari'), 'name' => 'story_btn1_text', 'type' => 'text', 'default_value' => __('Baca Selengkapnya', 'yiari')],
            ['key' => 'field_home_story_btn1_url', 'label' => __('Tombol 1 - URL', 'yiari'), 'name' => 'story_btn1_url', 'type' => 'url'],
            ['key' => 'field_home_story_btn2_text', 'label' => __('Tombol 2 - Teks', 'yiari'), 'name' => 'story_btn2_text', 'type' => 'text', 'default_value' => __('Donasi Sekarang', 'yiari')],
            ['key' => 'field_home_story_btn2_url', 'label' => __('Tombol 2 - URL', 'yiari'), 'name' => 'story_btn2_url', 'type' => 'url'],
            ['key' => 'field_home_story_image', 'label' => __('Gambar Utama / Slide Pertama', 'yiari'), 'name' => 'story_image', 'type' => 'image', 'return_format' => 'array'],
            [
                'key' => 'field_home_story_gallery',
                'label' => __('Gallery Carousel', 'yiari'),
                'name' => 'story_gallery',
                'type' => 'gallery',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'insert' => 'append',
                'library' => 'all',
                'instructions' => __('Tambahkan beberapa gambar untuk carousel. Gambar utama di atas akan dipakai sebagai slide pertama jika diisi.', 'yiari'),
            ],

            ['key' => 'field_home_approach_tab', 'label' => __('Approach Section', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_home_approach_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'approach_label', 'type' => 'text', 'default_value' => __('Program', 'yiari')],
            ['key' => 'field_home_approach_title', 'label' => __('Judul', 'yiari'), 'name' => 'approach_title', 'type' => 'text'],
            ['key' => 'field_home_approach_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'approach_desc', 'type' => 'textarea', 'rows' => 3],
            [
                'key' => 'field_home_approach_items', 'label' => __('Item Program', 'yiari'), 'name' => 'approach_items',
                'type' => 'repeater', 'min' => 1, 'max' => 8, 'layout' => 'table',
                'button_label' => __('Tambah Program', 'yiari'),
                'sub_fields' => [
                    ['key' => 'field_approach_title', 'label' => __('Judul', 'yiari'), 'name' => 'title', 'type' => 'text'],
                    ['key' => 'field_approach_subtitle', 'label' => __('Subtitle', 'yiari'), 'name' => 'subtitle', 'type' => 'text'],
                    ['key' => 'field_approach_details', 'label' => __('Deskripsi Detail', 'yiari'), 'name' => 'details', 'type' => 'textarea', 'rows' => 4],
                    ['key' => 'field_approach_button_text', 'label' => __('Teks Tombol', 'yiari'), 'name' => 'button_text', 'type' => 'text', 'default_value' => __('Lihat Program', 'yiari')],
                    ['key' => 'field_approach_button_url', 'label' => __('URL Tombol', 'yiari'), 'name' => 'button_url', 'type' => 'url'],
                    ['key' => 'field_approach_image', 'label' => __('Gambar', 'yiari'), 'name' => 'image', 'type' => 'image', 'return_format' => 'array'],
                ],
            ],

            ['key' => 'field_home_donate_tab', 'label' => __('Donate CTA Section', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_home_donate_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'donate_label', 'type' => 'text', 'default_value' => __('DUKUNGAN ANDA', 'yiari')],
            ['key' => 'field_home_donate_title', 'label' => __('Judul', 'yiari'), 'name' => 'donate_title', 'type' => 'text', 'default_value' => __('Setiap Donasi Menyelamatkan Nyawa', 'yiari')],
            ['key' => 'field_home_donate_text', 'label' => __('Teks', 'yiari'), 'name' => 'donate_text', 'type' => 'textarea', 'rows' => 3],
            ['key' => 'field_home_donate_btn1_text', 'label' => __('Tombol 1 - Teks', 'yiari'), 'name' => 'donate_btn1_text', 'type' => 'text', 'default_value' => __('Donasi Sekarang', 'yiari')],
            ['key' => 'field_home_donate_btn1_url', 'label' => __('Tombol 1 - URL', 'yiari'), 'name' => 'donate_btn1_url', 'type' => 'url'],
            ['key' => 'field_home_donate_btn2_text', 'label' => __('Tombol 2 - Teks', 'yiari'), 'name' => 'donate_btn2_text', 'type' => 'text', 'default_value' => __('Jadi Relawan', 'yiari')],
            ['key' => 'field_home_donate_btn2_url', 'label' => __('Tombol 2 - URL', 'yiari'), 'name' => 'donate_btn2_url', 'type' => 'url'],
            ['key' => 'field_home_donate_image', 'label' => __('Gambar CTA', 'yiari'), 'name' => 'donate_image', 'type' => 'image', 'return_format' => 'array'],
        ],
    ]);

    acf_add_local_field_group([
        'key' => 'group_about',
        'title' => __('About Us - Sections', 'yiari'),
        'location' => [[['param' => 'page_template', 'operator' => '==', 'value' => 'templates/about.php']]],
        'menu_order' => 10,
        'fields' => [
            ['key' => 'field_about_hero_tab', 'label' => __('Hero', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_about_hero_img', 'label' => __('Gambar Hero', 'yiari'), 'name' => 'about_hero_image', 'type' => 'image', 'return_format' => 'array'],
            ['key' => 'field_about_hero_title', 'label' => __('Judul', 'yiari'), 'name' => 'about_hero_title', 'type' => 'text', 'default_value' => __("Untuk Mereka yang\nTak Bisa Membela Diri", 'yiari')],
            ['key' => 'field_about_hero_text', 'label' => __('Teks', 'yiari'), 'name' => 'about_hero_text', 'type' => 'textarea', 'rows' => 4],
            ['key' => 'field_about_hero_btn1_text', 'label' => __('Tombol 1 Teks', 'yiari'), 'name' => 'about_btn1_text', 'type' => 'text', 'default_value' => __('Lihat Program Kami', 'yiari')],
            ['key' => 'field_about_hero_btn1_url', 'label' => __('Tombol 1 URL', 'yiari'), 'name' => 'about_btn1_url', 'type' => 'url'],
            ['key' => 'field_about_hero_btn2_text', 'label' => __('Tombol 2 Teks', 'yiari'), 'name' => 'about_btn2_text', 'type' => 'text', 'default_value' => __('Pelajari Lebih Lanjut', 'yiari')],
            ['key' => 'field_about_hero_btn2_url', 'label' => __('Tombol 2 URL', 'yiari'), 'name' => 'about_btn2_url', 'type' => 'url'],

            ['key' => 'field_about_vm_tab', 'label' => __('Visi & Misi', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_about_vm_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'vm_label', 'type' => 'text', 'default_value' => __('Arah Kami Bergerak', 'yiari')],
            ['key' => 'field_about_vm_section_title', 'label' => __('Judul Section', 'yiari'), 'name' => 'vm_section_title', 'type' => 'text', 'default_value' => __('Visi & Misi YIARI', 'yiari')],
            ['key' => 'field_about_vm_image', 'label' => __('Gambar', 'yiari'), 'name' => 'vm_image', 'type' => 'image', 'return_format' => 'array'],
            ['key' => 'field_about_vm_visi_title', 'label' => __('Label Visi', 'yiari'), 'name' => 'visi_label', 'type' => 'text', 'default_value' => __('Visi', 'yiari')],
            ['key' => 'field_about_vm_visi_text', 'label' => __('Teks Visi', 'yiari'), 'name' => 'visi_text', 'type' => 'textarea', 'rows' => 3],
            ['key' => 'field_about_vm_misi_title', 'label' => __('Label Misi', 'yiari'), 'name' => 'misi_label', 'type' => 'text', 'default_value' => __('Misi', 'yiari')],
            ['key' => 'field_about_vm_misi_text', 'label' => __('Teks Misi', 'yiari'), 'name' => 'misi_text', 'type' => 'textarea', 'rows' => 3],

            ['key' => 'field_about_timeline_tab', 'label' => __('Timeline', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_about_timeline_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'timeline_label', 'type' => 'text', 'default_value' => __('Dampak Nyata', 'yiari')],
            ['key' => 'field_about_timeline_title', 'label' => __('Judul', 'yiari'), 'name' => 'timeline_title', 'type' => 'text', 'default_value' => __('Jejak Dampak YIARI', 'yiari')],
            ['key' => 'field_about_timeline_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'timeline_desc', 'type' => 'textarea', 'rows' => 3],
            [
                'key' => 'field_about_timeline_items', 'label' => __('Item Timeline', 'yiari'), 'name' => 'timeline_items',
                'type' => 'repeater', 'min' => 1, 'max' => 12, 'layout' => 'row',
                'button_label' => __('Tambah Milestone', 'yiari'),
                'sub_fields' => [
                    ['key' => 'field_timeline_year', 'label' => __('Tahun', 'yiari'), 'name' => 'year', 'type' => 'text'],
                    ['key' => 'field_timeline_title', 'label' => __('Judul', 'yiari'), 'name' => 'title', 'type' => 'text'],
                    ['key' => 'field_timeline_text', 'label' => __('Teks', 'yiari'), 'name' => 'text', 'type' => 'textarea', 'rows' => 4],
                ],
            ],

            ['key' => 'field_about_org_tab', 'label' => __('Struktur Organisasi', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_about_org_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'org_label', 'type' => 'text', 'default_value' => __('Kepemimpinan Kami', 'yiari')],
            ['key' => 'field_about_org_title', 'label' => __('Judul', 'yiari'), 'name' => 'org_title', 'type' => 'text', 'default_value' => __('Struktur Organisasi', 'yiari')],
            ['key' => 'field_about_org_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'org_desc', 'type' => 'textarea', 'rows' => 3],
            [
                'key' => 'field_about_org_groups', 'label' => __('Kelompok Organisasi', 'yiari'), 'name' => 'org_groups',
                'type' => 'repeater', 'min' => 1, 'max' => 8, 'layout' => 'row',
                'button_label' => __('Tambah Kelompok', 'yiari'),
                'sub_fields' => [
                    ['key' => 'field_org_group_name', 'label' => __('Nama Kelompok', 'yiari'), 'name' => 'group_name', 'type' => 'text'],
                    [
                        'key' => 'field_org_members', 'label' => __('Anggota', 'yiari'), 'name' => 'members',
                        'type' => 'repeater', 'min' => 1, 'layout' => 'table',
                        'button_label' => __('Tambah Anggota', 'yiari'),
                        'sub_fields' => [
                            ['key' => 'field_member_photo', 'label' => __('Foto', 'yiari'), 'name' => 'photo', 'type' => 'image', 'return_format' => 'array'],
                            ['key' => 'field_member_name', 'label' => __('Nama', 'yiari'), 'name' => 'name', 'type' => 'text'],
                            ['key' => 'field_member_role', 'label' => __('Jabatan', 'yiari'), 'name' => 'role', 'type' => 'text'],
                        ],
                    ],
                ],
            ],
        ],
    ]);

    acf_add_local_field_group([
        'key' => 'group_landscape',
        'title' => __('Lanskap - Sections', 'yiari'),
        'location' => [[['param' => 'page_template', 'operator' => '==', 'value' => 'templates/lanskap.php']]],
        'menu_order' => 10,
        'fields' => [
            ['key' => 'field_landscape_hero_tab', 'label' => __('Hero', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_landscape_hero_img', 'label' => __('Gambar Hero', 'yiari'), 'name' => 'landscape_hero_image', 'type' => 'image', 'return_format' => 'array'],
            ['key' => 'field_landscape_hero_title', 'label' => __('Judul Hero', 'yiari'), 'name' => 'landscape_hero_title', 'type' => 'textarea', 'rows' => 3, 'default_value' => __('Di Garis Depan Perlindungan Satwa dan Hutan Indonesia', 'yiari')],
            ['key' => 'field_landscape_hero_text', 'label' => __('Teks Hero', 'yiari'), 'name' => 'landscape_hero_text', 'type' => 'textarea', 'rows' => 4],
            ['key' => 'field_landscape_hero_btn1_text', 'label' => __('Tombol 1 - Teks', 'yiari'), 'name' => 'landscape_hero_btn1_text', 'type' => 'text', 'default_value' => __('Lihat Lokasi Kegiatan', 'yiari')],
            ['key' => 'field_landscape_hero_btn1_url', 'label' => __('Tombol 1 - URL', 'yiari'), 'name' => 'landscape_hero_btn1_url', 'type' => 'url'],
            ['key' => 'field_landscape_hero_btn2_text', 'label' => __('Tombol 2 - Teks', 'yiari'), 'name' => 'landscape_hero_btn2_text', 'type' => 'text', 'default_value' => __('Pelajari Lebih Lanjut', 'yiari')],
            ['key' => 'field_landscape_hero_btn2_url', 'label' => __('Tombol 2 - URL', 'yiari'), 'name' => 'landscape_hero_btn2_url', 'type' => 'url'],

            ['key' => 'field_landscape_locations_tab', 'label' => __('Lokasi Program', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_landscape_locations_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'landscape_locations_label', 'type' => 'text', 'default_value' => __('WILAYAH KERJA KONSERVASI KAMI', 'yiari')],
            ['key' => 'field_landscape_locations_title', 'label' => __('Judul Section', 'yiari'), 'name' => 'landscape_locations_title', 'type' => 'textarea', 'rows' => 2, 'default_value' => __("Lokasi Kegiatan\nProgram", 'yiari')],
            ['key' => 'field_landscape_locations_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'landscape_locations_desc', 'type' => 'textarea', 'rows' => 3],
            [
                'key' => 'field_landscape_locations',
                'label' => __('Daftar Lokasi', 'yiari'),
                'name' => 'landscape_locations',
                'type' => 'repeater',
                'min' => 1,
                'max' => 12,
                'layout' => 'row',
                'button_label' => __('Tambah Lokasi', 'yiari'),
                'sub_fields' => [
                    ['key' => 'field_landscape_location_image', 'label' => __('Gambar', 'yiari'), 'name' => 'image', 'type' => 'image', 'return_format' => 'array'],
                    ['key' => 'field_landscape_location_title', 'label' => __('Judul', 'yiari'), 'name' => 'title', 'type' => 'text'],
                    ['key' => 'field_landscape_location_text', 'label' => __('Deskripsi', 'yiari'), 'name' => 'text', 'type' => 'textarea', 'rows' => 4],
                    ['key' => 'field_landscape_location_link_text', 'label' => __('Teks Link', 'yiari'), 'name' => 'link_text', 'type' => 'text', 'default_value' => __('Lihat Selengkapnya', 'yiari')],
                    ['key' => 'field_landscape_location_link_url', 'label' => __('URL Link', 'yiari'), 'name' => 'link_url', 'type' => 'url'],
                ],
            ],

            ['key' => 'field_landscape_bases_tab', 'label' => __('Basis Operasi', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_landscape_bases_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'landscape_bases_label', 'type' => 'text', 'default_value' => __('BASIS OPERASI', 'yiari')],
            ['key' => 'field_landscape_bases_title', 'label' => __('Judul Section', 'yiari'), 'name' => 'landscape_bases_title', 'type' => 'textarea', 'rows' => 2, 'default_value' => __("Pusat Utama\nOperasional", 'yiari')],
            ['key' => 'field_landscape_bases_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'landscape_bases_desc', 'type' => 'textarea', 'rows' => 3],
            [
                'key' => 'field_landscape_bases',
                'label' => __('Daftar Basis', 'yiari'),
                'name' => 'landscape_bases',
                'type' => 'repeater',
                'min' => 1,
                'max' => 6,
                'layout' => 'row',
                'button_label' => __('Tambah Basis', 'yiari'),
                'sub_fields' => [
                    ['key' => 'field_landscape_base_image', 'label' => __('Gambar', 'yiari'), 'name' => 'image', 'type' => 'image', 'return_format' => 'array'],
                    ['key' => 'field_landscape_base_title', 'label' => __('Judul', 'yiari'), 'name' => 'title', 'type' => 'text'],
                    ['key' => 'field_landscape_base_text', 'label' => __('Deskripsi', 'yiari'), 'name' => 'text', 'type' => 'textarea', 'rows' => 5],
                    ['key' => 'field_landscape_base_link_text', 'label' => __('Teks Link', 'yiari'), 'name' => 'link_text', 'type' => 'text', 'default_value' => __('Lihat Selengkapnya', 'yiari')],
                    ['key' => 'field_landscape_base_link_url', 'label' => __('URL Link', 'yiari'), 'name' => 'link_url', 'type' => 'url'],
                ],
            ],
        ],
    ]);

    acf_add_local_field_group([
        'key' => 'group_landscape_detail',
        'title' => __('Detail Lanskap - Sections', 'yiari'),
        'location' => [[['param' => 'page_template', 'operator' => '==', 'value' => 'templates/detail-lanskap.php']]],
        'menu_order' => 11,
        'fields' => [
            ['key' => 'field_landscape_detail_hero_tab', 'label' => __('Hero', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_landscape_detail_hero_img', 'label' => __('Gambar Hero', 'yiari'), 'name' => 'landscape_detail_hero_image', 'type' => 'image', 'return_format' => 'array'],
            ['key' => 'field_landscape_detail_hero_title', 'label' => __('Judul Hero', 'yiari'), 'name' => 'landscape_detail_hero_title', 'type' => 'textarea', 'rows' => 3, 'default_value' => __('Di Garis Depan Perlindungan Satwa dan Hutan Indonesia', 'yiari')],
            ['key' => 'field_landscape_detail_hero_text', 'label' => __('Teks Hero', 'yiari'), 'name' => 'landscape_detail_hero_text', 'type' => 'textarea', 'rows' => 4, 'default_value' => __('Dari hutan hujan Kalimantan hingga kawasan lindung Sumatra, kami bekerja di garis depan untuk melindungi ekosistem kritis dan keanekaragaman hayati Indonesia yang terancam.', 'yiari')],
            ['key' => 'field_landscape_detail_hero_btn1_text', 'label' => __('Tombol 1 - Teks', 'yiari'), 'name' => 'landscape_detail_hero_btn1_text', 'type' => 'text', 'default_value' => __('Lihat Lokasi Kegiatan', 'yiari')],
            ['key' => 'field_landscape_detail_hero_btn1_url', 'label' => __('Tombol 1 - URL', 'yiari'), 'name' => 'landscape_detail_hero_btn1_url', 'type' => 'url'],
            ['key' => 'field_landscape_detail_hero_btn2_text', 'label' => __('Tombol 2 - Teks', 'yiari'), 'name' => 'landscape_detail_hero_btn2_text', 'type' => 'text', 'default_value' => __('Pelajari Lebih Lanjut', 'yiari')],
            ['key' => 'field_landscape_detail_hero_btn2_url', 'label' => __('Tombol 2 - URL', 'yiari'), 'name' => 'landscape_detail_hero_btn2_url', 'type' => 'url'],

            ['key' => 'field_landscape_detail_intro_tab', 'label' => __('Mengapa Krusial', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_landscape_detail_intro_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'landscape_detail_intro_label', 'type' => 'text', 'default_value' => __('WILAYAH KUNCI KONSERVASI', 'yiari')],
            ['key' => 'field_landscape_detail_intro_title', 'label' => __('Judul Section', 'yiari'), 'name' => 'landscape_detail_intro_title', 'type' => 'textarea', 'rows' => 3, 'default_value' => __("Mengapa Ketapang\nSangat Krusial?", 'yiari')],
            ['key' => 'field_landscape_detail_intro_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'landscape_detail_intro_desc', 'type' => 'textarea', 'rows' => 4, 'default_value' => __('Kami beroperasi di wilayah-wilayah prioritas konservasi dengan kehadiran spesies kunci dan tingkat ancaman tinggi.', 'yiari')],
            ['key' => 'field_landscape_detail_intro_image', 'label' => __('Gambar Utama', 'yiari'), 'name' => 'landscape_detail_intro_image', 'type' => 'image', 'return_format' => 'array'],
            [
                'key' => 'field_landscape_detail_intro_points',
                'label' => __('Poin Kunci', 'yiari'),
                'name' => 'landscape_detail_intro_points',
                'type' => 'repeater',
                'min' => 1,
                'max' => 6,
                'layout' => 'row',
                'button_label' => __('Tambah Poin', 'yiari'),
                'sub_fields' => [
                    ['key' => 'field_landscape_detail_intro_point_image', 'label' => __('Gambar', 'yiari'), 'name' => 'image', 'type' => 'image', 'return_format' => 'array'],
                    ['key' => 'field_landscape_detail_intro_point_title', 'label' => __('Judul', 'yiari'), 'name' => 'title', 'type' => 'text'],
                    ['key' => 'field_landscape_detail_intro_point_text', 'label' => __('Deskripsi', 'yiari'), 'name' => 'text', 'type' => 'textarea', 'rows' => 3],
                ],
            ],

            ['key' => 'field_landscape_detail_program_tab', 'label' => __('Program', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_landscape_detail_program_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'landscape_detail_program_label', 'type' => 'text', 'default_value' => __('PROGRAM', 'yiari')],
            ['key' => 'field_landscape_detail_program_title', 'label' => __('Judul Section', 'yiari'), 'name' => 'landscape_detail_program_title', 'type' => 'textarea', 'rows' => 3, 'default_value' => __("Apa yang Kami\nLakukan di Ketapang", 'yiari')],
            ['key' => 'field_landscape_detail_program_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'landscape_detail_program_desc', 'type' => 'textarea', 'rows' => 4, 'default_value' => __('Lima program konservasi terintegrasi yang berjalan secara bersamaan untuk memastikan perlindungan jangka panjang.', 'yiari')],
            [
                'key' => 'field_landscape_detail_program_items',
                'label' => __('Daftar Program', 'yiari'),
                'name' => 'landscape_detail_program_items',
                'type' => 'repeater',
                'min' => 1,
                'max' => 8,
                'layout' => 'row',
                'button_label' => __('Tambah Program', 'yiari'),
                'sub_fields' => [
                    ['key' => 'field_landscape_detail_program_icon', 'label' => __('Ikon', 'yiari'), 'name' => 'icon', 'type' => 'image', 'return_format' => 'array'],
                    ['key' => 'field_landscape_detail_program_title_item', 'label' => __('Judul', 'yiari'), 'name' => 'title', 'type' => 'text'],
                    ['key' => 'field_landscape_detail_program_subtitle', 'label' => __('Subtitle', 'yiari'), 'name' => 'subtitle', 'type' => 'text'],
                    ['key' => 'field_landscape_detail_program_details', 'label' => __('Deskripsi Detail', 'yiari'), 'name' => 'details', 'type' => 'textarea', 'rows' => 4],
                    ['key' => 'field_landscape_detail_program_button_text', 'label' => __('Teks Tombol', 'yiari'), 'name' => 'button_text', 'type' => 'text', 'default_value' => __('Lihat Program', 'yiari')],
                    ['key' => 'field_landscape_detail_program_button_url', 'label' => __('URL Tombol', 'yiari'), 'name' => 'button_url', 'type' => 'url'],
                    ['key' => 'field_landscape_detail_program_image', 'label' => __('Gambar', 'yiari'), 'name' => 'image', 'type' => 'image', 'return_format' => 'array'],
                ],
            ],

            ['key' => 'field_landscape_detail_story_tab', 'label' => __('Dari Lapangan', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_landscape_detail_story_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'landscape_detail_story_label', 'type' => 'text', 'default_value' => __('DARI LAPANGAN', 'yiari')],
            ['key' => 'field_landscape_detail_story_title', 'label' => __('Judul Section', 'yiari'), 'name' => 'landscape_detail_story_title', 'type' => 'textarea', 'rows' => 3, 'default_value' => __("Pulih Pasca Kena\nJerat, Orangutan Siap\nKembali ke Habitatnya", 'yiari')],
            ['key' => 'field_landscape_detail_story_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'landscape_detail_story_desc', 'type' => 'textarea', 'rows' => 4, 'default_value' => __('Satwa ditemukan terluka akibat jerat, orangutan ini menjalani perawatan intensif dan kini tengah bersiap kembali ke alam liar.', 'yiari')],
            ['key' => 'field_landscape_detail_story_btn1_text', 'label' => __('Tombol 1 - Teks', 'yiari'), 'name' => 'landscape_detail_story_btn1_text', 'type' => 'text', 'default_value' => __('Baca Selengkapnya', 'yiari')],
            ['key' => 'field_landscape_detail_story_btn1_url', 'label' => __('Tombol 1 - URL', 'yiari'), 'name' => 'landscape_detail_story_btn1_url', 'type' => 'url'],
            ['key' => 'field_landscape_detail_story_btn2_text', 'label' => __('Tombol 2 - Teks', 'yiari'), 'name' => 'landscape_detail_story_btn2_text', 'type' => 'text', 'default_value' => __('Donasi Sekarang', 'yiari')],
            ['key' => 'field_landscape_detail_story_btn2_url', 'label' => __('Tombol 2 - URL', 'yiari'), 'name' => 'landscape_detail_story_btn2_url', 'type' => 'url'],
            ['key' => 'field_landscape_detail_story_image', 'label' => __('Gambar Utama / Slide Pertama', 'yiari'), 'name' => 'landscape_detail_story_image', 'type' => 'image', 'return_format' => 'array'],
            ['key' => 'field_landscape_detail_story_gallery', 'label' => __('Gallery Carousel', 'yiari'), 'name' => 'landscape_detail_story_gallery', 'type' => 'gallery', 'return_format' => 'array', 'preview_size' => 'thumbnail', 'insert' => 'append', 'library' => 'all'],

            ['key' => 'field_landscape_detail_updates_tab', 'label' => __('Sorotan Lapangan', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_landscape_detail_updates_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'landscape_detail_updates_label', 'type' => 'text', 'default_value' => __('SOROTAN LAPANGAN', 'yiari')],
            ['key' => 'field_landscape_detail_updates_title', 'label' => __('Judul Section', 'yiari'), 'name' => 'landscape_detail_updates_title', 'type' => 'textarea', 'rows' => 2, 'default_value' => __("Update dari\nKetapang", 'yiari')],
            ['key' => 'field_landscape_detail_updates_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'landscape_detail_updates_desc', 'type' => 'textarea', 'rows' => 4, 'default_value' => __('Beragam cerita, berita, dan informasi terbaru seputar kegiatan dan perkembangan konservasi di wilayah ini.', 'yiari')],
            ['key' => 'field_landscape_detail_updates_category', 'label' => __('Kategori Artikel', 'yiari'), 'name' => 'landscape_detail_updates_category', 'type' => 'taxonomy', 'taxonomy' => 'category', 'field_type' => 'select', 'return_format' => 'id', 'allow_null' => 1, 'add_term' => 0, 'save_terms' => 0, 'load_terms' => 0],
            ['key' => 'field_landscape_detail_updates_count', 'label' => __('Jumlah Artikel', 'yiari'), 'name' => 'landscape_detail_updates_count', 'type' => 'number', 'default_value' => 9, 'min' => 3, 'max' => 12, 'step' => 1],
            ['key' => 'field_landscape_detail_updates_button_text', 'label' => __('Teks Tombol Bawah', 'yiari'), 'name' => 'landscape_detail_updates_button_text', 'type' => 'text', 'default_value' => __('Muat Lebih Banyak', 'yiari')],
        ],
    ]);

    acf_add_local_field_group([
        'key' => 'group_donation_page',
        'title' => __('Donasi - Sections', 'yiari'),
        'location' => [[['param' => 'page_template', 'operator' => '==', 'value' => 'templates/donasi.php']]],
        'menu_order' => 12,
        'fields' => [
            ['key' => 'field_donation_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'donation_label', 'type' => 'text', 'default_value' => __('AKSI NYATA', 'yiari')],
            ['key' => 'field_donation_title', 'label' => __('Judul Halaman', 'yiari'), 'name' => 'donation_title', 'type' => 'textarea', 'rows' => 3, 'default_value' => __("Karena Kontribusi\nAnda", 'yiari')],
            ['key' => 'field_donation_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'donation_desc', 'type' => 'textarea', 'rows' => 4, 'default_value' => __('Membantu menyelamatkan, merawat, dan mengembalikan satwa ke alamnya, serta menjaga keseimbangan ekosistem.', 'yiari')],
            ['key' => 'field_donation_image', 'label' => __('Gambar Utama', 'yiari'), 'name' => 'donation_image', 'type' => 'image', 'return_format' => 'array'],
            ['key' => 'field_donation_supporters_text', 'label' => __('Teks Dukungan Donatur', 'yiari'), 'name' => 'donation_supporters_text', 'type' => 'text', 'default_value' => __('Lebih dari 1 Juta orang sudah berdonasi', 'yiari')],
            ['key' => 'field_donation_supporter_avatars', 'label' => __('Avatar Donatur', 'yiari'), 'name' => 'donation_supporter_avatars', 'type' => 'gallery', 'return_format' => 'array', 'preview_size' => 'thumbnail', 'insert' => 'append', 'library' => 'all'],
            ['key' => 'field_donation_quote', 'label' => __('Testimoni', 'yiari'), 'name' => 'donation_quote', 'type' => 'textarea', 'rows' => 4, 'default_value' => __('“Semangat terus tim YIARI. Semoga semakin banyak hewan-hewan kita yang bisa diselamatkan”', 'yiari')],
            ['key' => 'field_donation_donor_name', 'label' => __('Nama Donatur', 'yiari'), 'name' => 'donation_donor_name', 'type' => 'text', 'default_value' => __('Ariani Namira', 'yiari')],
            ['key' => 'field_donation_donor_meta', 'label' => __('Keterangan Donatur', 'yiari'), 'name' => 'donation_donor_meta', 'type' => 'text', 'default_value' => __('Sudah berdonasi Rp 50.000', 'yiari')],
            ['key' => 'field_donation_form_title', 'label' => __('Judul Panel Form', 'yiari'), 'name' => 'donation_form_title', 'type' => 'text', 'default_value' => __('Lengkapi Kontribusi Anda', 'yiari')],
            ['key' => 'field_donation_form_desc', 'label' => __('Deskripsi Panel Form', 'yiari'), 'name' => 'donation_form_desc', 'type' => 'textarea', 'rows' => 3, 'default_value' => __('Pilih jumlah donasi dan lengkapi data diri secara singkat. Semua transaksi aman dan terenkripsi.', 'yiari')],
            ['key' => 'field_donation_form_button_text', 'label' => __('Teks Tombol Form', 'yiari'), 'name' => 'donation_form_button_text', 'type' => 'text', 'default_value' => __('Kirim Donasi', 'yiari')],
        ],
    ]);

    acf_add_local_field_group([
        'key' => 'group_donation_thankyou_page',
        'title' => __('Donasi Thank You - Sections', 'yiari'),
        'location' => [[['param' => 'page_template', 'operator' => '==', 'value' => 'templates/donasi-thankyou.php']]],
        'menu_order' => 13,
        'fields' => [
            ['key' => 'field_donation_thankyou_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'donation_thankyou_label', 'type' => 'text', 'default_value' => __('DUKUNGAN ANDA', 'yiari')],
            ['key' => 'field_donation_thankyou_title', 'label' => __('Judul Utama', 'yiari'), 'name' => 'donation_thankyou_title', 'type' => 'textarea', 'rows' => 3, 'default_value' => __("Terima Kasih atas\nDukungan Anda", 'yiari')],
            ['key' => 'field_donation_thankyou_desc', 'label' => __('Deskripsi Utama', 'yiari'), 'name' => 'donation_thankyou_desc', 'type' => 'textarea', 'rows' => 4, 'default_value' => __('Donasi Anda berhasil kami terima. Kontribusi Anda sangat berarti bagi keberlangsungan satwa liar di Indonesia, membantu kami terus melindungi keanekaragaman hayati nusantara.', 'yiari')],
            ['key' => 'field_donation_thankyou_note', 'label' => __('Catatan Tambahan', 'yiari'), 'name' => 'donation_thankyou_note', 'type' => 'textarea', 'rows' => 3, 'default_value' => __('Bukti konfirmasi telah dikirimkan ke email Anda. Silakan periksa folder spam jika tidak menemukannya di kotak masuk utama. Butuh bantuan? Hubungi kami di informasi@yiari.or.id', 'yiari')],
            ['key' => 'field_donation_thankyou_image', 'label' => __('Gambar Utama', 'yiari'), 'name' => 'donation_thankyou_image', 'type' => 'image', 'return_format' => 'array'],
            ['key' => 'field_donation_thankyou_explore_label', 'label' => __('Label Eksplorasi', 'yiari'), 'name' => 'donation_thankyou_explore_label', 'type' => 'text', 'default_value' => __('EKSPLORASI', 'yiari')],
            ['key' => 'field_donation_thankyou_explore_title', 'label' => __('Judul Eksplorasi', 'yiari'), 'name' => 'donation_thankyou_explore_title', 'type' => 'textarea', 'rows' => 3, 'default_value' => __("Terus Berjalan\nBersama Kami", 'yiari')],
            ['key' => 'field_donation_thankyou_explore_desc', 'label' => __('Deskripsi Eksplorasi', 'yiari'), 'name' => 'donation_thankyou_explore_desc', 'type' => 'textarea', 'rows' => 3, 'default_value' => __('Eksplorasi lebih dalam bagaimana kontribusi Anda membentuk masa depan yang lebih baik bagi satwa liar Indonesia.', 'yiari')],
            [
                'key' => 'field_donation_thankyou_cards',
                'label' => __('Kartu Eksplorasi', 'yiari'),
                'name' => 'donation_thankyou_cards',
                'type' => 'repeater',
                'min' => 1,
                'max' => 6,
                'layout' => 'row',
                'button_label' => __('Tambah Kartu', 'yiari'),
                'sub_fields' => [
                    ['key' => 'field_donation_thankyou_card_image', 'label' => __('Gambar', 'yiari'), 'name' => 'image', 'type' => 'image', 'return_format' => 'array'],
                    ['key' => 'field_donation_thankyou_card_title', 'label' => __('Judul', 'yiari'), 'name' => 'title', 'type' => 'text'],
                    ['key' => 'field_donation_thankyou_card_text', 'label' => __('Deskripsi', 'yiari'), 'name' => 'text', 'type' => 'textarea', 'rows' => 3],
                    ['key' => 'field_donation_thankyou_card_link_text', 'label' => __('Teks Link', 'yiari'), 'name' => 'link_text', 'type' => 'text', 'default_value' => __('Lihat Selengkapnya', 'yiari')],
                    ['key' => 'field_donation_thankyou_card_link_url', 'label' => __('URL Link', 'yiari'), 'name' => 'link_url', 'type' => 'url'],
                ],
            ],
        ],
    ]);

    acf_add_local_field_group([
        'key' => 'group_join_page',
        'title' => __('Bergabung - Sections', 'yiari'),
        'location' => [[['param' => 'page_template', 'operator' => '==', 'value' => 'templates/bergabung.php']]],
        'menu_order' => 14,
        'fields' => [
            ['key' => 'field_join_hero_tab', 'label' => __('Hero', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_join_hero_image', 'label' => __('Gambar Hero', 'yiari'), 'name' => 'join_hero_image', 'type' => 'image', 'return_format' => 'array'],
            ['key' => 'field_join_hero_title', 'label' => __('Judul Hero', 'yiari'), 'name' => 'join_hero_title', 'type' => 'textarea', 'rows' => 3, 'default_value' => __("Bersama Kita Bisa\nMelindungi Satwa\ndan Hutan Indonesia", 'yiari')],
            ['key' => 'field_join_hero_text', 'label' => __('Teks Hero', 'yiari'), 'name' => 'join_hero_text', 'type' => 'textarea', 'rows' => 4, 'default_value' => __('Setiap langkah kecil yang Anda ambil hari ini menjadi fondasi bagi keberlangsungan ekosistem nusantara di masa depan. Bergabunglah dalam misi kolaboratif untuk menyelamatkan habitat yang terancam.', 'yiari')],
            ['key' => 'field_join_hero_btn1_text', 'label' => __('Tombol 1 - Teks', 'yiari'), 'name' => 'join_hero_btn1_text', 'type' => 'text', 'default_value' => __('Mulai Bergabung', 'yiari')],
            ['key' => 'field_join_hero_btn1_url', 'label' => __('Tombol 1 - URL', 'yiari'), 'name' => 'join_hero_btn1_url', 'type' => 'url'],
            ['key' => 'field_join_hero_btn2_text', 'label' => __('Tombol 2 - Teks', 'yiari'), 'name' => 'join_hero_btn2_text', 'type' => 'text', 'default_value' => __('Pelajari Lebih Lanjut', 'yiari')],
            ['key' => 'field_join_hero_btn2_url', 'label' => __('Tombol 2 - URL', 'yiari'), 'name' => 'join_hero_btn2_url', 'type' => 'url'],

            ['key' => 'field_join_program_tab', 'label' => __('Program', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_join_program_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'join_program_label', 'type' => 'text', 'default_value' => __('PROGRAM MAGANG & RELAWAN', 'yiari')],
            ['key' => 'field_join_program_title', 'label' => __('Judul Section', 'yiari'), 'name' => 'join_program_title', 'type' => 'textarea', 'rows' => 3, 'default_value' => __("Rasakan Pengalaman\nNyata Bersama Tim\nKonservasi YIARI", 'yiari')],
            ['key' => 'field_join_program_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'join_program_desc', 'type' => 'textarea', 'rows' => 4, 'default_value' => __('Program ini membuka kesempatan bagi pelajar dan mahasiswa untuk terlibat langsung dalam berbagai kegiatan konservasi, mulai dari magang, relawan, penelitian, hingga pengabdian lainnya di lingkungan YIARI.', 'yiari')],
            ['key' => 'field_join_program_image', 'label' => __('Gambar Utama', 'yiari'), 'name' => 'join_program_image', 'type' => 'image', 'return_format' => 'array'],
            [
                'key' => 'field_join_program_items',
                'label' => __('Daftar Peran', 'yiari'),
                'name' => 'join_program_items',
                'type' => 'repeater',
                'min' => 1,
                'max' => 6,
                'layout' => 'row',
                'button_label' => __('Tambah Peran', 'yiari'),
                'sub_fields' => [
                    ['key' => 'field_join_program_item_title', 'label' => __('Judul', 'yiari'), 'name' => 'title', 'type' => 'text'],
                    ['key' => 'field_join_program_item_text', 'label' => __('Deskripsi', 'yiari'), 'name' => 'text', 'type' => 'textarea', 'rows' => 3],
                ],
            ],

            ['key' => 'field_join_story_tab', 'label' => __('Cerita Lapangan', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_join_story_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'join_story_label', 'type' => 'text', 'default_value' => __('CERITA DARI LAPANGAN', 'yiari')],
            ['key' => 'field_join_story_title', 'label' => __('Judul Section', 'yiari'), 'name' => 'join_story_title', 'type' => 'textarea', 'rows' => 3, 'default_value' => __("Pengalaman Nyata\nBersama YIARI", 'yiari')],
            ['key' => 'field_join_story_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'join_story_desc', 'type' => 'textarea', 'rows' => 4, 'default_value' => __('Kisah mahasiswa, relawan, dan peserta magang yang terlibat langsung dalam kegiatan konservasi, penelitian, dan kehidupan di lapangan.', 'yiari')],
            ['key' => 'field_join_story_link_text', 'label' => __('Teks Link Section', 'yiari'), 'name' => 'join_story_link_text', 'type' => 'text', 'default_value' => __('Lihat Semua Cerita Magang', 'yiari')],
            ['key' => 'field_join_story_link_url', 'label' => __('URL Link Section', 'yiari'), 'name' => 'join_story_link_url', 'type' => 'url'],
            ['key' => 'field_join_story_category', 'label' => __('Kategori Artikel', 'yiari'), 'name' => 'join_story_category', 'type' => 'taxonomy', 'taxonomy' => 'category', 'field_type' => 'multi_select', 'return_format' => 'id', 'allow_null' => 1, 'add_term' => 0, 'save_terms' => 0, 'load_terms' => 0, 'instructions' => __('Bisa pilih lebih dari satu kategori, misalnya cerita magang dan cerita penelitian.', 'yiari')],
            ['key' => 'field_join_story_count', 'label' => __('Jumlah Artikel', 'yiari'), 'name' => 'join_story_count', 'type' => 'number', 'default_value' => 3, 'min' => 3, 'max' => 6, 'step' => 1],

            ['key' => 'field_join_steps_tab', 'label' => __('Langkah Pendaftaran', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_join_steps_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'join_steps_label', 'type' => 'text', 'default_value' => __('LANGKAH AWAL ANDA', 'yiari')],
            ['key' => 'field_join_steps_title', 'label' => __('Judul Section', 'yiari'), 'name' => 'join_steps_title', 'type' => 'textarea', 'rows' => 2, 'default_value' => __('Proses Pendaftaran', 'yiari')],
            ['key' => 'field_join_steps_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'join_steps_desc', 'type' => 'textarea', 'rows' => 3, 'default_value' => __('Mulai langkah pertama Anda untuk terlibat langsung dalam upaya konservasi, ikuti prosesnya dan jadilah bagian dari perubahan.', 'yiari')],
            [
                'key' => 'field_join_steps_items',
                'label' => __('Daftar Langkah', 'yiari'),
                'name' => 'join_steps_items',
                'type' => 'repeater',
                'min' => 1,
                'max' => 6,
                'layout' => 'row',
                'button_label' => __('Tambah Langkah', 'yiari'),
                'sub_fields' => [
                    ['key' => 'field_join_steps_item_title', 'label' => __('Judul', 'yiari'), 'name' => 'title', 'type' => 'text'],
                    ['key' => 'field_join_steps_item_text', 'label' => __('Deskripsi', 'yiari'), 'name' => 'text', 'type' => 'textarea', 'rows' => 3],
                ],
            ],

            ['key' => 'field_join_form_tab', 'label' => __('Formulir', 'yiari'), 'name' => '', 'type' => 'tab', 'placement' => 'top'],
            ['key' => 'field_join_form_label', 'label' => __('Label Atas', 'yiari'), 'name' => 'join_form_label', 'type' => 'text', 'default_value' => __('MULAI DARI SINI', 'yiari')],
            ['key' => 'field_join_form_title', 'label' => __('Judul Section', 'yiari'), 'name' => 'join_form_title', 'type' => 'textarea', 'rows' => 2, 'default_value' => __('Formulir Pendaftaran', 'yiari')],
            ['key' => 'field_join_form_desc', 'label' => __('Deskripsi', 'yiari'), 'name' => 'join_form_desc', 'type' => 'textarea', 'rows' => 3, 'default_value' => __('Lengkapi formulir ini dan ambil langkah nyata untuk terlibat langsung dalam konservasi.', 'yiari')],
            ['key' => 'field_join_form_shortcode', 'label' => __('Shortcode Fluent Form', 'yiari'), 'name' => 'join_form_shortcode', 'type' => 'text', 'default_value' => '[fluentform id="1"]'],
        ],
    ]);
});
